import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ShipflowOverlay } from "./shipflow-overlay-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Change Workbench",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {process.env.NODE_ENV === "development" || process.env.SHIPFLOW_OVERLAY_ENABLED === "true" ? (
          <ShipflowOverlay />
        ) : null}
      </body>
    </html>
  );
}
